export const DEVICE_ACTIONS = {
    FETCH_DEVICES: 'FETCH_DEVICES',
    SHOW_DEVICES: 'SHOW_DEVICES',
    SEND_DEVICE: 'SEND_DEVICE',
    DELETE_DEVICE: 'DELETE_DEVICE',
    UPDATE_DEVICE: 'FETCH_DEVICE',
}