export const WATER_ACTIONS = {
    FETCH_EVENTS: 'FETCH_EVENTS',
    SHOW_EVENTS: 'SHOW_EVENTS',
    SEND_EVENT: 'SEND_EVENT',
    POST_EVENT: 'POST_EVENT',
    DELETE_EVENT: 'DELETE_EVENT',
    UPDATE_EVENT: 'UPDATE_EVENT'
}